//! Every man page must still say what its command's `--help` says.
//!
//! Issue #281. `volume resume`'s clap doc comment described behaviour that
//! commit `8b061b7` had removed — it claimed resume would quarantine an
//! already-sealed tape, when resume now re-enters confirm instead — and
//! `docs/man/tapectl-volume-resume.1` carried the same dead sentence. The
//! two were consistent with each other and both wrong, while the recovery
//! line `volume write` printed at the same moment said the opposite. An
//! operator checking the documentation before acting on a freshly sealed
//! cartridge would have been sent to `volume abort`, orphaning a good tape.
//!
//! That was the THIRD operator-facing string in one week to outlive the
//! behaviour it described (#209, #274, #281), so the guard is deliberately
//! general rather than a string check on the one sentence that was wrong.
//!
//! **What this can and cannot catch.** Man pages are generated by hand
//! (`cargo run --example gen_man`), never by the build, so the realistic
//! failure is a help text edited without a regen — a man page asserting
//! behaviour that the source itself no longer claims. That is exactly what
//! this catches, and it caught it for free the moment the fix for #281 was
//! written. What it cannot catch is BOTH texts being updated together and
//! both being wrong about the code; nothing textual can. The pairing that
//! covers that is a behavioural test next to the code, which is why this
//! file is a drift alarm and not a correctness proof.

use clap::CommandFactory;
use std::path::PathBuf;

/// Undo `clap_mangen`'s roff escaping and collapse whitespace, so a man
/// page's prose can be compared with the clap text it was generated from.
///
/// Only the escapes `clap_mangen` actually emits are handled — `\-` for
/// hyphens, `\*(Aq` for apostrophes (via the `.ds Aq` macro at the top of
/// every page), and the `\fB`/`\fI`/`\fR` font selectors. A future escape
/// this misses would show up as a spurious failure naming the command,
/// which is the right way to find out.
fn normalize(s: &str) -> String {
    let mut out = s.to_string();
    for (from, to) in [
        ("\\*(Aq", "'"),
        ("\\fB", ""),
        ("\\fI", ""),
        ("\\fR", ""),
        ("\\-", "-"),
        ("\\&", ""),
    ] {
        out = out.replace(from, to);
    }
    out.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Walk the clap tree, yielding `(man page stem, long help text)` for every
/// command that has help text of its own.
fn commands_with_help() -> Vec<(String, String)> {
    fn walk(cmd: &clap::Command, path: &[String], out: &mut Vec<(String, String)>) {
        for sub in cmd.get_subcommands() {
            let mut p = path.to_vec();
            p.push(sub.get_name().to_string());

            // `long_about` when the doc comment had more than one
            // paragraph, `about` otherwise — the same choice clap_mangen
            // makes when it renders DESCRIPTION.
            let help = sub
                .get_long_about()
                .or_else(|| sub.get_about())
                .map(|s| s.to_string());
            if let Some(help) = help {
                out.push((format!("tapectl-{}", p.join("-")), help));
            }
            walk(sub, &p, out);
        }
    }
    let root = tapectl::cli::Cli::command();
    let mut out = Vec::new();
    walk(&root, &[], &mut out);
    out
}

/// The regression guard for issue #281: a man page that no longer agrees
/// with its own `--help`.
///
/// Fails by NAME, listing every stale page, because "some man page is
/// stale" is not actionable and the fix is always the same one command.
#[test]
fn every_man_page_still_matches_its_commands_help() {
    let man_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("docs/man");
    assert!(
        man_dir.is_dir(),
        "docs/man must exist — regenerate with `cargo run --example gen_man`"
    );

    let mut stale: Vec<String> = Vec::new();
    let mut checked = 0usize;

    for (stem, help) in commands_with_help() {
        let page = man_dir.join(format!("{stem}.1"));
        let Ok(raw) = std::fs::read_to_string(&page) else {
            // A command with no page of its own is not this test's
            // business; `gen_man`'s coverage is its own question.
            continue;
        };
        checked += 1;
        let page_text = normalize(&raw);

        // Compare the FIRST paragraph only. It is the one `.SH NAME` and
        // `.SH DESCRIPTION` both carry, it is what `--help` shows without
        // `--help` being asked twice, and it is where the #281 sentence
        // lived. Comparing every paragraph would also work but makes a
        // failure harder to read for no extra catching power.
        let first_para = help.split("\n\n").next().unwrap_or(&help);
        let needle = normalize(first_para);
        if !needle.is_empty() && !page_text.contains(&needle) {
            stale.push(format!(
                "  {stem}: help says {:?}\n      but the page does not contain it",
                needle.chars().take(120).collect::<String>()
            ));
        }
    }

    assert!(
        checked > 20,
        "expected to check many man pages, checked only {checked} — the \
         clap-tree-to-filename mapping has probably drifted, which would \
         make this test pass by checking nothing"
    );
    assert!(
        stale.is_empty(),
        "{} man page(s) no longer match their command's --help. Run \
         `cargo run --example gen_man` and commit docs/man:\n{}",
        stale.len(),
        stale.join("\n")
    );
}

/// Issue #281's own specific claim, kept as a named assertion because the
/// general test above would go quiet the moment someone regenerated the man
/// page from a help text that had been changed BACK.
///
/// `InterruptedSession::resume_checking`'s `AlreadySealed` arm routes
/// through `resume_reconfirm_eligible` and returns `ResumeOutcome::
/// Confirming` — no seal call, no quarantine — when the tape proves it is
/// this session's own. The help must not tell the operator otherwise, since
/// the message `volume write` prints at that exact moment sends them here.
#[test]
fn volume_resume_help_does_not_promise_to_quarantine_an_already_sealed_tape() {
    let root = tapectl::cli::Cli::command();
    let volume = root
        .get_subcommands()
        .find(|c| c.get_name() == "volume")
        .expect("volume subcommand");
    let resume = volume
        .get_subcommands()
        .find(|c| c.get_name() == "resume")
        .expect("volume resume subcommand");
    let help = resume
        .get_long_about()
        .or_else(|| resume.get_about())
        .expect("volume resume must have help text")
        .to_string();

    // The falsified sentence, in the shape it actually shipped.
    let quarantines_sealed = help.contains("quarantining the volume)")
        && help.contains("tape is already\n    /// sealed")
        || help.contains("or if the tape is already sealed");
    assert!(
        !quarantines_sealed,
        "resume's help must not claim an already-sealed tape is refused and \
         quarantined — commit 8b061b7 made that false, and `volume write` \
         prints \"run `tapectl volume resume <label>`\" in exactly that \
         situation. Help was:\n{help}"
    );

    // The positive control: without it, the assertion above would also pass
    // for help text that said nothing about sealed tapes at all, which is
    // the silence that caused #281 rather than a fix for it.
    assert!(
        help.contains("RE-CONFIRMED") || help.to_lowercase().contains("re-confirm"),
        "resume's help must say what DOES happen to an already-sealed tape, \
         not merely omit the wrong claim. Help was:\n{help}"
    );
}
