//! Render the clap command tree as GitHub Markdown — shared by
//! `examples/gen_cli_md.rs` (which writes `docs/cli/`) and
//! `tests/cli_md_fresh.rs` (which fails when the committed pages are stale).
//!
//! One page per top-level command (`docs/cli/<command>.md`) holding that
//! command and every subcommand beneath it, plus `docs/cli/README.md`, the
//! index. GitHub renders troff man pages as raw text, so for a reader on
//! GitHub these pages ARE the reference; they come from the same `Cli` the
//! binary parses, so they cannot describe a flag that does not exist.

use clap::{Arg, Command};

/// `(relative path, contents)` for every page, index first.
pub fn render_all(cmd: &Command) -> Vec<(String, String)> {
    let mut pages = vec![("README.md".to_string(), render_index(cmd))];
    for sub in visible_subcommands(cmd) {
        let mut out = String::new();
        out.push_str(&format!(
            "<!-- Generated by `cargo run --example gen_cli_md` from the clap definitions. Do not edit. -->\n\n# tapectl {}\n\n",
            sub.get_name()
        ));
        out.push_str("[All commands](README.md)\n\n");
        render_command(&mut out, sub, &format!("tapectl {}", sub.get_name()), 2);
        pages.push((format!("{}.md", sub.get_name()), out));
    }
    pages
}

fn visible_subcommands(cmd: &Command) -> Vec<&Command> {
    cmd.get_subcommands()
        .filter(|s| s.get_name() != "help" && !s.is_hide_set())
        .collect()
}

fn anchor(path: &str) -> String {
    // GitHub's heading slug: lowercase, spaces to dashes, drop punctuation.
    path.to_lowercase()
        .chars()
        .filter_map(|c| match c {
            ' ' => Some('-'),
            c if c.is_alphanumeric() || c == '-' || c == '_' => Some(c),
            _ => None,
        })
        .collect()
}

fn text(s: Option<&clap::builder::StyledStr>) -> String {
    s.map(|s| s.to_string())
        .unwrap_or_default()
        .trim()
        .to_string()
}

fn about(cmd: &Command) -> String {
    let long = text(cmd.get_long_about());
    if long.is_empty() {
        text(cmd.get_about())
    } else {
        long
    }
}

fn first_line(s: &str) -> String {
    s.lines().next().unwrap_or("").trim().to_string()
}

fn render_index(cmd: &Command) -> String {
    let mut out = String::new();
    out.push_str("<!-- Generated by `cargo run --example gen_cli_md` from the clap definitions. Do not edit. -->\n\n");
    out.push_str("# tapectl command reference\n\n");
    out.push_str(&format!("{}\n\n", about(cmd)));
    out.push_str(
        "Every command, subcommand and flag the binary accepts, generated from the same\n",
    );
    out.push_str("definitions it parses. For what to *do* with them, start at the\n");
    out.push_str("[documentation index](../README.md).\n\n");
    out.push_str(
        "## Global options\n\nAccepted by every command, before or after the subcommand.\n\n",
    );
    let globals: Vec<&Arg> = cmd
        .get_arguments()
        .filter(|a| a.is_global_set() && !a.is_hide_set() && !is_auto(a))
        .collect();
    for a in &globals {
        out.push_str(&arg_item(a));
    }
    out.push_str("\n## Commands\n\n| Command | What it does |\n|---|---|\n");
    for sub in visible_subcommands(cmd) {
        let name = sub.get_name();
        out.push_str(&format!(
            "| [`{name}`]({name}.md) | {} |\n",
            cell(&first_line(&text(sub.get_about())))
        ));
        for s2 in visible_subcommands(sub) {
            let path = format!("tapectl {name} {}", s2.get_name());
            out.push_str(&format!(
                "| &nbsp;&nbsp;[`{name} {}`]({name}.md#{}) | {} |\n",
                s2.get_name(),
                anchor(&path),
                cell(&first_line(&text(s2.get_about())))
            ));
        }
    }
    out
}

fn cell(s: &str) -> String {
    s.replace('|', "\\|")
}

fn is_auto(a: &Arg) -> bool {
    matches!(a.get_id().as_str(), "help" | "version")
}

fn render_command(out: &mut String, cmd: &Command, path: &str, depth: usize) {
    let hashes = "#".repeat(depth.min(6));
    if depth > 2 {
        out.push_str(&format!("{hashes} {path}\n\n"));
    }
    let desc = about(cmd);
    if !desc.is_empty() {
        out.push_str(&format!("{desc}\n\n"));
    }
    let mut c = cmd.clone().bin_name(path.to_string());
    let usage = c.render_usage().to_string();
    let usage = usage.trim_start_matches("Usage:").trim();
    out.push_str(&format!("```text\n{usage}\n```\n\n"));

    let subs = visible_subcommands(cmd);
    if !subs.is_empty() {
        out.push_str("**Subcommands**\n\n");
        for s in &subs {
            let p = format!("{path} {}", s.get_name());
            out.push_str(&format!(
                "- [`{}`](#{}) — {}\n",
                s.get_name(),
                anchor(&p),
                first_line(&text(s.get_about()))
            ));
        }
        out.push('\n');
    }

    let positionals: Vec<&Arg> = cmd
        .get_arguments()
        .filter(|a| a.is_positional() && !a.is_hide_set())
        .collect();
    if !positionals.is_empty() {
        out.push_str("**Arguments**\n\n");
        for a in positionals {
            out.push_str(&arg_item(a));
        }
        out.push('\n');
    }
    let options: Vec<&Arg> = cmd
        .get_arguments()
        .filter(|a| !a.is_positional() && !a.is_hide_set() && !a.is_global_set() && !is_auto(a))
        .collect();
    if !options.is_empty() {
        out.push_str("**Options**\n\n");
        for a in options {
            out.push_str(&arg_item(a));
        }
        out.push('\n');
    }
    for s in subs {
        render_command(out, s, &format!("{path} {}", s.get_name()), depth + 1);
    }
}

fn arg_item(a: &Arg) -> String {
    let names: Vec<String> = a
        .get_value_names()
        .map(|v| v.iter().map(|n| n.to_string()).collect())
        .unwrap_or_default();
    let value = if names.is_empty() {
        String::new()
    } else {
        format!(" <{}>", names.join("> <"))
    };
    let label = if a.is_positional() {
        let n = names
            .first()
            .cloned()
            .unwrap_or_else(|| a.get_id().to_string().to_uppercase());
        if a.is_required_set() {
            format!("<{n}>")
        } else {
            format!("[{n}]")
        }
    } else {
        let mut l = String::new();
        if let Some(s) = a.get_short() {
            l.push_str(&format!("-{s}, "));
        }
        if let Some(long) = a.get_long() {
            l.push_str(&format!("--{long}"));
        }
        let takes_value = a.get_num_args().map(|r| r.takes_values()).unwrap_or(false);
        if takes_value {
            l.push_str(&value);
        }
        l
    };
    let mut help = text(a.get_long_help());
    if help.is_empty() {
        help = text(a.get_help());
    }
    let mut extras = Vec::new();
    if a.is_required_set() && !a.is_positional() {
        extras.push("required".to_string());
    }
    let defaults: Vec<String> = a
        .get_default_values()
        .iter()
        .map(|v| v.to_string_lossy().to_string())
        .collect();
    if !defaults.is_empty() && a.get_num_args().map(|r| r.takes_values()).unwrap_or(false) {
        extras.push(format!("default: `{}`", defaults.join(", ")));
    }
    let pv: Vec<String> = a
        .get_possible_values()
        .iter()
        .filter(|v| !v.is_hide_set())
        .map(|v| format!("`{}`", v.get_name()))
        .collect();
    if !pv.is_empty() {
        extras.push(format!("one of {}", pv.join(", ")));
    }
    let extra = if extras.is_empty() {
        String::new()
    } else {
        format!(" *({})*", extras.join("; "))
    };
    // Multi-paragraph help: keep paragraphs, indented under the bullet.
    let help = help.replace("\n\n", "\n\n  ").replace('\n', "\n  ");
    format!("- `{label}`{extra} — {help}\n")
}
