.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tapectl-cartridge 1  "tapectl-cartridge " 
.SH NAME
tapectl\-cartridge \- Manage physical cartridges
.SH SYNOPSIS
\fBtapectl cartridge\fR [\fB\-\-json\fR] [\fB\-\-dry\-run\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage physical cartridges
.SH OPTIONS
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-dry\-run\fR
Show what would be done without making changes
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Path to config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
tapectl\-cartridge\-register(1)
Register a physical cartridge
.TP
tapectl\-cartridge\-list(1)
List cartridges
.TP
tapectl\-cartridge\-info(1)
Show cartridge details
.TP
tapectl\-cartridge\-mark\-erased(1)
Mark a cartridge as erased (available for reuse)
.TP
tapectl\-cartridge\-help(1)
Print this message or the help of the given subcommand(s)
