.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tapectl-volume-compact 1  "tapectl-volume-compact " 
.SH NAME
tapectl\-volume\-compact \- Interactive compaction: read + write + finish in one flow
.SH SYNOPSIS
\fBtapectl volume compact\fR [\fB\-\-device\fR] [\fB\-\-json\fR] [\fB\-\-dry\-run\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fILABEL\fR> 
.SH DESCRIPTION
Interactive compaction: read + write + finish in one flow
.SH OPTIONS
.TP
\fB\-\-device\fR \fI<DEVICE>\fR [default: /dev/nst0]
Tape device path
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-dry\-run\fR
Show what would be done without making changes
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Path to config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fILABEL\fR>
Source volume label
