.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tapectl-location-add 1  "tapectl-location-add " 
.SH NAME
tapectl\-location\-add \- Add a storage location
.SH SYNOPSIS
\fBtapectl location add\fR [\fB\-d\fR|\fB\-\-description\fR] [\fB\-\-json\fR] [\fB\-\-dry\-run\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Add a storage location
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-description\fR \fI<DESCRIPTION>\fR
Description
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-dry\-run\fR
Show what would be done without making changes
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Path to config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Location name (e.g., "home\-rack", "parents\-house")
