.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tapectl-volume-compact-write 1  "tapectl-volume-compact-write " 
.SH NAME
tapectl\-volume\-compact\-write \- Write compaction slices from staging to destination (compaction step 2)
.SH SYNOPSIS
\fBtapectl volume compact\-write\fR <\fB\-\-destination\fR> [\fB\-\-json\fR] [\fB\-\-device\fR] [\fB\-\-dry\-run\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Write compaction slices from staging to destination (compaction step 2)
.SH OPTIONS
.TP
\fB\-\-destination\fR \fI<DESTINATION>\fR
Destination volume label
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-device\fR \fI<DEVICE>\fR [default: /dev/nst0]
Tape device path
.TP
\fB\-\-dry\-run\fR
Show what would be done without making changes
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Path to config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
