.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tapectl-key-export 1  "tapectl-key-export " 
.SH NAME
tapectl\-key\-export \- Export a public key to stdout
.SH SYNOPSIS
\fBtapectl key export\fR [\fB\-\-json\fR] [\fB\-\-dry\-run\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIALIAS\fR> 
.SH DESCRIPTION
Export a public key to stdout
.SH OPTIONS
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-dry\-run\fR
Show what would be done without making changes
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Path to config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIALIAS\fR>
Key alias
