.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tapectl-cartridge-info 1  "tapectl-cartridge-info " 
.SH NAME
tapectl\-cartridge\-info \- Show cartridge details
.SH SYNOPSIS
\fBtapectl cartridge info\fR [\fB\-\-json\fR] [\fB\-\-dry\-run\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIBARCODE\fR> 
.SH DESCRIPTION
Show cartridge details
.SH OPTIONS
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-dry\-run\fR
Show what would be done without making changes
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Path to config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIBARCODE\fR>
Barcode
