.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tapectl-tenant-reassign 1  "tapectl-tenant-reassign " 
.SH NAME
tapectl\-tenant\-reassign \- Reassign all units from one tenant to another
.SH SYNOPSIS
\fBtapectl tenant reassign\fR [\fB\-\-json\fR] <\fB\-\-to\fR> [\fB\-\-dry\-run\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISOURCE\fR> 
.SH DESCRIPTION
Reassign all units from one tenant to another
.SH OPTIONS
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-to\fR \fI<TO>\fR
Destination tenant name
.TP
\fB\-\-dry\-run\fR
Show what would be done without making changes
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Path to config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISOURCE\fR>
Source tenant name
