.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tapectl-catalog-locate 1  "tapectl-catalog-locate " 
.SH NAME
tapectl\-catalog\-locate \- Show which volume(s) contain a unit
.SH SYNOPSIS
\fBtapectl catalog locate\fR [\fB\-\-json\fR] [\fB\-\-dry\-run\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIUNIT\fR> 
.SH DESCRIPTION
Show which volume(s) contain a unit
.SH OPTIONS
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-dry\-run\fR
Show what would be done without making changes
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Path to config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIUNIT\fR>
Unit name
