.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tapectl-snapshot-diff 1  "tapectl-snapshot-diff " 
.SH NAME
tapectl\-snapshot\-diff \- Compare two snapshot versions of a unit
.SH SYNOPSIS
\fBtapectl snapshot diff\fR [\fB\-\-json\fR] <\fB\-\-v1\fR> [\fB\-\-dry\-run\fR] <\fB\-\-v2\fR> [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Compare two snapshot versions of a unit
.SH OPTIONS
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-v1\fR \fI<V1>\fR
First version number
.TP
\fB\-\-dry\-run\fR
Show what would be done without making changes
.TP
\fB\-\-v2\fR \fI<V2>\fR
Second version number
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Path to config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Unit name
