.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tapectl-location 1  "tapectl-location " 
.SH NAME
tapectl\-location \- Manage storage locations
.SH SYNOPSIS
\fBtapectl location\fR [\fB\-\-json\fR] [\fB\-\-dry\-run\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage storage locations
.SH OPTIONS
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-dry\-run\fR
Show what would be done without making changes
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Path to config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
tapectl\-location\-add(1)
Add a storage location
.TP
tapectl\-location\-list(1)
List locations
.TP
tapectl\-location\-info(1)
Show location details
.TP
tapectl\-location\-rename(1)
Rename a location
.TP
tapectl\-location\-help(1)
Print this message or the help of the given subcommand(s)
