.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tapectl-volume-write 1  "tapectl-volume-write " 
.SH NAME
tapectl\-volume\-write \- Write staged data to volume
.SH SYNOPSIS
\fBtapectl volume write\fR [\fB\-\-device\fR] [\fB\-\-json\fR] [\fB\-\-dry\-run\fR] [\fB\-\-force\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fILABEL\fR> 
.SH DESCRIPTION
Write staged data to volume
.SH OPTIONS
.TP
\fB\-\-device\fR \fI<DEVICE>\fR [default: /dev/nst0]
Tape device path
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-\-dry\-run\fR
Show what would be done without making changes
.TP
\fB\-\-force\fR
See `volume init \-\-force` — same override, same limits
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Path to config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fILABEL\fR>
Volume label
